# Generated by Django 6.0.2 on 2026-02-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('In progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
